### ISSUE TITLE
@slack is broken since v2

### ISSUE THREAD

**Issue by AdrienPoupa** [laravel/envoy#188]
- Envoy Version: 2.0.1
- Laravel Version: 7.5.2

### Description:

@slack in @finished is broken since I updated to v2:

```
PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\_idn_uri_convert() in /home/adrien/code/einsteinfiv2/vendor/guzzlehttp/guzzle/src/Client.php:220
Stack trace:
#0 /home/adrien/code/einsteinfiv2/vendor/guzzlehttp/guzzle/src/Client.php(155): GuzzleHttp\Client->buildUri(Object(GuzzleHttp\Psr7\Uri), Array)
#1 /home/adrien/code/einsteinfiv2/vendor/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Client->requestAsync('post', 'https://hooks.s...', Array)
#2 /home/adrien/code/einsteinfiv2/vendor/guzzlehttp/guzzle/src/Client.php(96): GuzzleHttp\Client->request('post', 'https://hooks.s...', Array)
#3 /home/adrien/.config/composer/vendor/laravel/envoy/src/Slack.php(89): GuzzleHttp\Client->__call('post', Array)
#4 /home/adrien/code/einsteinfiv2/Envoy0c8c66e074beeabc7205a20ce72131bf.php(298): Laravel\Envoy\Slack->send()
#5 [internal function]: Laravel\Envoy\TaskContainer->{closure}()
#6 /home/adrien/.config/composer/vendor/laravel/envoy/src/Console/RunCommand.php(88): call_user_func(Object(Closure))
#7 /home/adrien/. in /home/adrien/code/einsteinfiv2/vendor/guzzlehttp/guzzle/src/Client.php on line 220
```

My Envoy relevant section:

```
@finished
    echo "Envoy deployment complete.\r\n";
    if ($env != 'local') {
        @slack($slack, '#my-channel', "Deployment on {$env} complete - Release {$release} - Commit {$latestCommit}")
    }
@endfinished
```

The same code worked fine for v1

**Comment by AdrienPoupa** [comment]
Nevermind, turns out Guzzle 6.5.0 was installed and I needed 6.5.2.

Maybe the composer.lock should be updated to require Guzzle 6.5 and above?
